name: Deploy JAR to AWS EC2

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the deployment on

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: |
        mkdir -p ~/.ssh
        # Write SSH private key to file
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        # Add EC2 host to known_hosts to avoid SSH warnings
        ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

    - name: Deploy JAR to AWS EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        # Copy the JAR file to the EC2 instance
        scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ./BankingManagementSystemMongo.jar ${EC2_USER}@${EC2_HOST}:/home/${EC2_USER}/

        # Run the JAR file on the EC2 instance
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} "java -jar /home/${EC2_USER}/BankingManagementSystemMongo.jar"
