name: Deploy JAR to AWS EC2

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the deployment on

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to EC2
       
      env:
          SSH_PRIVATE_KEY: ${{ secrets['SSH_PRIVATE_KEY'] }}
          SSH_HOST: ${{ secrets['EC2_HOST'] }}
          SSH_USER: ${{ secrets['EC2_USER'] }}
      run: |
          echo "$SSH_PRIVATE_KEY" > shik.pem
          chmod 600 shik.pem
          ssh -o StrictHostKeyChecking=no -i shik.pem $SSH_USER@${{ secrets['EC2_HOST'] }} << 'EOF'

    - name: Deploy JAR to AWS EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        # Check if the JAR file exists
        if [ ! -f ./BankingManagementSystemMongo.jar ]; then
          echo "JAR file not found!"
          exit 1
        fi

        # Copy the JAR file to the EC2 instance
        scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ./BankingManagementSystemMongo.jar ${EC2_USER}@${EC2_HOST}:/home/${EC2_USER}/

        # Run the JAR file on the EC2 instance
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} "java -jar /home/${EC2_USER}/BankingManagementSystemMongo.jar"
        EOF
        
